#!/bin/sh

# Generate utf8 include with xxd
xxd -i src/utf8.h  | sed 's/\([0-9a-f]\)$/\0, 0x00/' > src/strutf8.xxd
xxd -i src/arena.h | sed 's/\([0-9a-f]\)$/\0, 0x00/' > src/strarena.xxd

# Clean

if [ "$1" = "install" ]; then
  # Build release
  cc src/pgen.c -o pgen -O3 -march=native

  # Install binary
  sudo cp pgen /bin/pgen
  echo "Installed pgen."
elif [ "$1" = "profile" ]; then
  # Build pgen and generate tokenizer and parser.
  cc src/pgen.c -o pgen
  ./pgen examples/pl0.tok examples/pl0.peg -o examples/pl0.h

  cd examples/

  # Build pl0 tokenizer/parser for profiling
  cc pl0.c -O3 -march=native -ggdb3

  # Profile with Callgrind
  valgrind --tool=callgrind ./a.out 2>/dev/null
  callgrind_annotate callgrind.out* > calls
  nano calls

  # Profile with Cachegrind
  valgrind --tool=cachegrind --branch-sim=yes ./a.out 2>/dev/null
  cg_annotate cachegrind.out.* > cache
  nano cache

  # Dump the instructions
  objdump -D a.out > dump
  nano dump

  # Make a flamegraph
  #flamegraph ./a.out

  # Clean up
  rm dump calls cache cachegrind.out.* callgrind.out.* 2>/dev/null
  cd ..
else
  # Build debug
  clang src/pgen.c -o pgen -fsanitize=address -g -Wall -Wextra -Wpedantic -Wno-unused-parameter -Wno-unused-variable

  # Build and run pl0 example
  ./pgen examples/pl0.tok examples/pl0.peg -o examples/pl0.h
  cd examples/
  clang pl0.c -fsanitize=address -g
  cc pl0.c
  ./a.out
  cd ..
fi




