PLUS:  "+";
MINUS: "-";
MULT:  "*";
DIV:   "/";
OPEN:  "(";
CLOSE: ")";

NUMBER: 2 {
  (0, [-+]) -> 1;
  ((0, 1, 2), [0-9]) -> 2;
};

WS: 1 {
  ((0, 1), [ \n\r\t]) -> 1;
};


expr <- next

sumexpr  <- rule:next
           (PLUS  n:next {rule=node(PLUS, rule, n)}
           /MINUS n:next {rule=node(MINUS, rule, n)})*

multexpr <- rule:next
           (MULT n:next {rule=node(MULT, rule, n)}
           /DIV  n:next {rule=node(DIV,  rule, n)})*

baseexpr <- OPEN rule:expr CLOSE
          / NUMBER

